### ISSUE TITLE
I cannot make apk

### ISSUE THREAD

**Issue by aimkoh** [bigbluebutton/bbb-air-client#51]
I cannot make apk but it can debug on device.I don't understand

**Comment by taiji1985** [comment]
maybe you need a android key .  the key canbe created by flexbuilder .

**Comment by fcecagno** [comment]
If you're able to debug on device, you're already creating an APK. Check your build directory.
Also, you'll need to create an Android key in order to sign the app properly, for more information, see http://developer.android.com/tools/publishing/app-signing.html
