### ISSUE TITLE
Question: Is AEC problem exist in bbb-air?

### ISSUE THREAD

**Issue by sevengo8378** [bigbluebutton/bbb-air-client#52]
issue on adobe bug base:
https://bugbase.adobe.com/index.cfm?event=bug&id=2901450

**Comment by ffdixon** [comment]
Hi Seven,

As the bug says, there is no AEC in the air client.  This means users of the Air client on a mobile device will need to use earbuds if they want to activate their microphone.  It's not a showstopper (we will deliver a mobile client using Air), but it would be nice if it did support AEC.

**Comment by sevengo8378** [comment]
I was searching an alternative solution. After read many articles it seems headset is the only choice... 
Really frustrating, hope adobe will add this enhancement asap.
